import type { HomeAssistant } from "./types";

const EN = {
  "task.load_error": "Tasks could not be loaded.",
  "due.none": "No due date",
  "date.yesterday": "Yesterday",
  "date.days_ago": "{count} days ago",
  "date.today": "Today",
  "date.tomorrow": "Tomorrow",
  "date.today_time": "Today {time}",
  "date.yesterday_time": "Yesterday {time}",
  "edit.duration_error": "Duration must be a whole number between 1 and 1440 minutes.",
  "error.not_visible": "This task is not visible to you.",
  "error.not_assigned": "This task is not assigned to you.",
  "error.not_open": "This task is no longer open.",
  "error.person_disabled": "This person is not enabled.",
  "error.action_failed": "Action failed.",
  "card.unavailable": "ChoreFlow unavailable",
  "card.sensor_missing": "The required sensor {entity} was not found. Check the card configuration and the ChoreFlow integration.",
  "count.open": "{count} open",
  "tab.tasks": "Tasks",
  "tab.history": "History",
  "action.create": "Create task",
  "action.complete": "Complete",
  "action.edit": "Edit",
  "action.snooze": "Remind later",
  "action.correct": "Correct",
  "action.revert_completion": "Undo completion",
  "action.close": "Close",
  "action.cancel": "Cancel",
  "action.save": "Save",
  "action.create_short": "Create",
  "action.retry": "Try again",
  "action.load_more": "Load more",
  "stat.open": "Open",
  "stat.due": "Due",
  "stat.overdue": "Overdue",
  "stat.completed_today": "Completed today",
  "filter.all": "All",
  "filter.room_aria": "Filter by room",
  "filter.all_rooms": "All rooms",
  "filter.category_aria": "Filter by category",
  "filter.all_categories": "All categories",
  "filter.group_room": "By room",
  "tasks.loading": "Loading tasks …",
  "tasks.refreshing": "Updating tasks …",
  "tasks.preview_total": "Partial view: {shown} of {total} open tasks are shown from the sensor preview.",
  "tasks.preview_truncated": "Partial view: The sensor preview is truncated; more open tasks are not currently loaded.",
  "tasks.empty": "Nothing is open for this filter.",
  "tasks.no_room": "No room",
  "urgency.overdue": "Overdue · {count} {unit}",
  "urgency.today_important": "Due today · Important",
  "urgency.today": "Due today",
  "urgency.tomorrow_important": "Due tomorrow · Important",
  "urgency.soon_important": "Due soon · Important",
  "unit.day": "day",
  "unit.days": "days",
  "unit.minutes_short": "min",
  "task.snoozed_tomorrow": "Snoozed until tomorrow",
  "task.completed": "Completed",
  "history.title": "History",
  "history.loading": "Loading…",
  "history.empty": "No entries yet.",
  "history.completed": "Completed",
  "history.completed_todo": "Completed (to-do)",
  "history.corrected": "Corrected",
  "history.snoozed": "Reminded later",
  "history.created": "Created",
  "history.updated": "Updated",
  "history.deleted": "Deleted",
  "history.notified": "Notified",
  "history.missed": "Missed (away)",
  "history.expired": "Expired",
  "history.from_todo": "From to-do",
  "history.calendar_created": "Calendar created",
  "history.calendar_removed": "Calendar removed",
  "person.who": "Who are you?",
  "person.none": "No persons found. Set persons or default_person in the card configuration.",
  "edit.title": "Edit task",
  "field.title": "Title",
  "field.description": "Description",
  "field.room": "Room",
  "field.category": "Category",
  "field.importance": "Importance",
  "field.duration": "Duration (min)",
  "field.due_date": "Due date",
  "field.person": "Person",
  "importance.high": "High",
  "importance.normal": "Normal",
  "importance.low": "Low",
  "recurrence.title": "Recurrence",
  "recurrence.once": "Once",
  "recurrence.every_n_days": "Every N days",
  "recurrence.weekdays": "Weekdays",
  "recurrence.interval": "Interval (days)",
  "weekday.mon": "Mon",
  "weekday.tue": "Tue",
  "weekday.wed": "Wed",
  "weekday.thu": "Thu",
  "weekday.fri": "Fri",
  "weekday.sat": "Sat",
  "weekday.sun": "Sun",
  "create.title": "New task",
  "create.title_placeholder": "e.g. clean bathroom",
  "create.room_placeholder": "Kitchen",
  "create.category_placeholder": "Cleaning",
  "create.due": "Due on",
  "create.visibility_assignment": "Visibility & assignment",
  "create.visible_to": "Visible to",
  "create.all_persons": "All persons",
  "create.selected": "Selected",
  "create.assignment": "Assignment",
  "create.random": "Random",
  "create.fixed_person": "Specific person",
  "create.choose_person": "Choose person…",
  "create.calendar_export": "Calendar export",
  "create.calendar_entity": "Calendar entity (optional)",
  "create.calendar_help": "When provided, the due date is created as an event in the selected calendar.",
  "editor.global_sensors": "Global sensors",
  "editor.open_required": "Open tasks (required)",
  "editor.due": "Due tasks",
  "editor.overdue": "Overdue tasks",
  "editor.completed_today": "Completed today",
  "editor.completed_week": "Completed this week",
  "editor.active_chains": "Active chains",
  "editor.persons": "Persons",
  "editor.remove": "Remove",
  "editor.open": "Open",
  "editor.remaining_today": "Remaining today",
  "editor.has_due": "Has due tasks",
  "editor.chain_active": "Chain active",
  "editor.add_person": "+ Add person",
  "editor.options": "Options",
  "editor.show_create": "Show create dialog",
  "editor.show_history": "Show history tab",
  "editor.default_person": "Default person",
} as const;

export type TranslationKey = keyof typeof EN;

const DE: Record<TranslationKey, string> = {
  "task.load_error": "Aufgaben konnten nicht geladen werden.",
  "due.none": "Kein Termin",
  "date.yesterday": "Gestern",
  "date.days_ago": "vor {count} Tagen",
  "date.today": "Heute",
  "date.tomorrow": "Morgen",
  "date.today_time": "Heute {time}",
  "date.yesterday_time": "Gestern {time}",
  "edit.duration_error": "Die Dauer muss eine ganze Zahl zwischen 1 und 1440 Minuten sein.",
  "error.not_visible": "Aufgabe ist dir nicht sichtbar.",
  "error.not_assigned": "Aufgabe ist dir nicht zugewiesen.",
  "error.not_open": "Aufgabe ist nicht mehr offen.",
  "error.person_disabled": "Person ist nicht aktiviert.",
  "error.action_failed": "Aktion fehlgeschlagen.",
  "card.unavailable": "ChoreFlow nicht verfügbar",
  "card.sensor_missing": "Der Pflicht-Sensor {entity} wurde nicht gefunden. Prüfe die Card-Konfiguration und die ChoreFlow-Integration.",
  "count.open": "{count} offen",
  "tab.tasks": "Aufgaben",
  "tab.history": "Verlauf",
  "action.create": "Aufgabe erstellen",
  "action.complete": "Erledigen",
  "action.edit": "Bearbeiten",
  "action.snooze": "Später erinnern",
  "action.correct": "Korrigieren",
  "action.revert_completion": "Erledigung rückgängig machen",
  "action.close": "Schließen",
  "action.cancel": "Abbrechen",
  "action.save": "Speichern",
  "action.create_short": "Erstellen",
  "action.retry": "Erneut versuchen",
  "action.load_more": "Mehr laden",
  "stat.open": "Offen",
  "stat.due": "Fällig",
  "stat.overdue": "Überfällig",
  "stat.completed_today": "Heute erledigt",
  "filter.all": "Alle",
  "filter.room_aria": "Raum filtern",
  "filter.all_rooms": "Alle Räume",
  "filter.category_aria": "Kategorie filtern",
  "filter.all_categories": "Alle Kategorien",
  "filter.group_room": "Nach Raum",
  "tasks.loading": "Aufgaben werden geladen …",
  "tasks.refreshing": "Aufgaben werden aktualisiert …",
  "tasks.preview_total": "Teilansicht: {shown} von {total} offenen Aufgaben werden aus der Sensor-Vorschau angezeigt.",
  "tasks.preview_truncated": "Teilansicht: Die Sensor-Vorschau ist gekürzt; weitere offene Aufgaben sind derzeit nicht geladen.",
  "tasks.empty": "Für diesen Filter ist nichts offen.",
  "tasks.no_room": "Ohne Raum",
  "urgency.overdue": "Überfällig · {count} {unit}",
  "urgency.today_important": "Heute fällig · Wichtig",
  "urgency.today": "Heute fällig",
  "urgency.tomorrow_important": "Morgen fällig · Wichtig",
  "urgency.soon_important": "Bald fällig · Wichtig",
  "unit.day": "Tag",
  "unit.days": "Tage",
  "unit.minutes_short": "Min",
  "task.snoozed_tomorrow": "Aufgeschoben bis morgen",
  "task.completed": "Erledigt",
  "history.title": "Verlauf",
  "history.loading": "Lädt…",
  "history.empty": "Noch keine Einträge.",
  "history.completed": "Erledigt",
  "history.completed_todo": "Erledigt (To-do)",
  "history.corrected": "Korrigiert",
  "history.snoozed": "Später erinnert",
  "history.created": "Erstellt",
  "history.updated": "Geändert",
  "history.deleted": "Gelöscht",
  "history.notified": "Benachrichtigt",
  "history.missed": "Verpasst (abwesend)",
  "history.expired": "Abgelaufen",
  "history.from_todo": "Aus To-do",
  "history.calendar_created": "Kalender erstellt",
  "history.calendar_removed": "Kalender entfernt",
  "person.who": "Wer bist du?",
  "person.none": "Keine Personen gefunden. Bitte persons oder default_person in der Kartenkonfiguration setzen.",
  "edit.title": "Aufgabe bearbeiten",
  "field.title": "Titel",
  "field.description": "Beschreibung",
  "field.room": "Raum",
  "field.category": "Kategorie",
  "field.importance": "Wichtigkeit",
  "field.duration": "Dauer (Min)",
  "field.due_date": "Fälligkeitsdatum",
  "field.person": "Person",
  "importance.high": "Hoch",
  "importance.normal": "Normal",
  "importance.low": "Niedrig",
  "recurrence.title": "Wiederholung",
  "recurrence.once": "Einmalig",
  "recurrence.every_n_days": "Alle N Tage",
  "recurrence.weekdays": "Wochentage",
  "recurrence.interval": "Intervall (Tage)",
  "weekday.mon": "Mo",
  "weekday.tue": "Di",
  "weekday.wed": "Mi",
  "weekday.thu": "Do",
  "weekday.fri": "Fr",
  "weekday.sat": "Sa",
  "weekday.sun": "So",
  "create.title": "Neue Aufgabe",
  "create.title_placeholder": "z. B. Bad putzen",
  "create.room_placeholder": "Küche",
  "create.category_placeholder": "Reinigung",
  "create.due": "Fällig am",
  "create.visibility_assignment": "Sichtbarkeit & Zuweisung",
  "create.visible_to": "Sichtbar für",
  "create.all_persons": "Alle Personen",
  "create.selected": "Ausgewählte",
  "create.assignment": "Zuweisung",
  "create.random": "Zufällig",
  "create.fixed_person": "Feste Person",
  "create.choose_person": "Person wählen…",
  "create.calendar_export": "Kalender-Export",
  "create.calendar_entity": "Kalender-Entität (optional)",
  "create.calendar_help": "Falls angegeben, wird der Fälligkeitstermin als Termin im gewählten Kalender angelegt.",
  "editor.global_sensors": "Globale Sensoren",
  "editor.open_required": "Offene Aufgaben (Pflicht)",
  "editor.due": "Fällige Aufgaben",
  "editor.overdue": "Überfällige Aufgaben",
  "editor.completed_today": "Heute erledigt",
  "editor.completed_week": "Diese Woche erledigt",
  "editor.active_chains": "Aktive Ketten",
  "editor.persons": "Personen",
  "editor.remove": "Entfernen",
  "editor.open": "Offen",
  "editor.remaining_today": "Verbleibend heute",
  "editor.has_due": "Hat fällige Aufgaben",
  "editor.chain_active": "Kette aktiv",
  "editor.add_person": "+ Person hinzufügen",
  "editor.options": "Optionen",
  "editor.show_create": "Erstellen-Dialog anzeigen",
  "editor.show_history": "Verlauf-Tab anzeigen",
  "editor.default_person": "Standard-Person",
};

const TRANSLATIONS: Record<"de" | "en", Record<TranslationKey, string>> = {
  de: DE,
  en: EN,
};

function language(hass: HomeAssistant | undefined): "de" | "en" {
  const configured = hass?.locale?.language ?? hass?.language ?? "en";
  return configured.toLowerCase().startsWith("de") ? "de" : "en";
}

export function formatLocale(hass: HomeAssistant | undefined): string {
  return hass?.locale?.language ?? hass?.language ?? "en";
}

export function localize(
  hass: HomeAssistant | undefined,
  key: TranslationKey,
  replacements: Record<string, string | number> = {}
): string {
  let value = TRANSLATIONS[language(hass)][key];
  for (const [name, replacement] of Object.entries(replacements)) {
    value = value.replaceAll(`{${name}}`, String(replacement));
  }
  return value;
}
